name: Use actions Workflow 
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code // clone the repository
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: shows the Node version
        run: node --version
      - name: Install dependencies
        run: npm install